

#define     I_MSG_BAUDRATE_SAVE_SUCCESS     "Baudrate successful saved."
#define     I_MSG_DATABITS_SAVE_SUCCESS     "Databits successful saved."
#define     I_MSG_PARITY_SAVE_SUCCESS       "Parity successful saved."
#define     I_MSG_STOPPBITS_SAVE_SUCCESS    "Stoppbits successful saved."
#define     I_MSG_SEND_OPERATION_COMPLETE   "Send-Operation complete. Bytes transferred: "
#define     I_MSG_RECEIVE_OPERATION_COMPLETE    "Receive-Operation complete. Bytes received: "
#define     I_MSG_CONFIG_RESET_SUCCESS      "Configuration successful set to default."
#define     I_MSG_AUTODETECT_SAVE_SUCCESS   "Auto-detect successful saved."
#define     I_MSG_SSID_SAVE_SUCCESS         "SSID successful saved."
#define     I_MSG_PASSWORD_SAVE_SUCCESS     "Password successful saved."

#define     E_MSG_INVALID_DATA              "Invalid data."
#define     E_MSG_INVALID_BAUD_VALUE        "Error invalid baud value (invalid index)"
#define     E_MSG_BAUDRATE_SAVE_FAILED      "Error occured while saving Baudrate."
#define     E_MSG_DATABITS_SAVE_FAILED      "Error occured while saving databits."
#define     E_MSG_PARITY_SAVE_FAILED        "Error occured while saving parity."
#define     E_MSG_STOPPBITS_SAVE_FAILED     "Error occured while saving stoppbits."
#define     E_MSG_CONFIG_RESET_ERROR        "Error occured while resetting the device."
#define     E_MSG_TRANSMISSION_ALREADY_IN_PROGRESS  "Transmission already in progress."
#define     E_MSG_INVALID_SEND_IS_ACTIVE    "Invalid command. Cannot stop receiving: Send operation is active."
#define     E_MSG_AUTODETECT_SAVE_FAILED    "Error occured while saving auto-detect"
#define     E_MSG_SSID_SAVE_FAILED          "Error occured while saving SSID"
#define     E_MSG_PASSWORD_SAVE_FAILED      "Error occured while saving Password"
#define     E_MSG_MAXIMUM_CHAR_EXCEEDED     "Error: maximum character size exceeded"
#define     E_MSG_UNKNOWN_COMMAND           "Error: unknown command"


#define     TERM_INCOMING_SSID_CONFIG_REQUEST       "ssid"
#define     TERM_INCOMING_PASSWORD_CONFIG_REQUEST   "password"

#define     TERM_OUTGOING_HELP_RESPONSE_1           "This is the serial configuration interface for this device.\n"
#define     TERM_OUTGOING_HELP_RESPONSE_2           "To change the SSID (wifi-name) enter 'ssid' and follow the prompt.\n"
#define     TERM_OUTGOING_HELP_RESPONSE_3           "To change the Password for the AccessPoint enter 'password' and follow the prompt.\n"
#define     TERM_OUTGOING_SSID_ENTER_PROMPT         "Please enter wifi SSID > "
#define     TERM_OUTGOING_PASSWORD_ENTER_PROMPT     "Please enter wifi Password > "